[unix_http_server]
file=/var/www/storage/logs/supervisor.sock
chmod=0700

[supervisord]
nodaemon=true
logfile=/var/www/storage/logs/supervisord.log
pidfile=/var/www/storage/logs/supervisord.pid
childlogdir=/var/www/storage/logs

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/www/storage/logs/supervisor.sock

[program:notification-packages-default]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/artisan queue:work rabbitmq --queue=notification-packages.default --sleep=3
directory=/var/www
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/storage/logs/worker-packages-default.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3

[program:notifications-high]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/artisan queue:work rabbitmq --queue=notifications.high --sleep=1
directory=/var/www
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=3
redirect_stderr=true
stdout_logfile=/var/www/storage/logs/worker-notifications-high.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3

[program:notifications-default]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/artisan queue:work rabbitmq --queue=notifications.default --sleep=3
directory=/var/www
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/storage/logs/worker-notifications-default.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3